# -*- coding: utf-8 -*-
"""Alternative.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11iwlWYH-j7bfAxeEjpFC00O9EDJFoQsR

### Alternative.py
"""

# Create a sentence string and equating to a variable
sentence = "how are you doing"

# Trying to know length of string
length = len(sentence)
print(length)


new_sentence = ''

for num in range(0, length):
    if num % 2 == 0:
      new_sentence += sentence[num].upper()

    else:

      new_sentence += sentence[num].lower()

print(f'The new alternate character sentence is:  {new_sentence}')

# creating a string and equating to a variable
word = 'I am in the garden'

# Splitting  the string abd printing out
split_word = word.split()
print(split_word)
print(len(split_word))

# Creating an empty string and equating to a variable
new_word = ''

for i in range(len(split_word)):
      if i % 2 == 0:
        new_word += split_word[i].lower() + ' '

      else:

        new_word += split_word[i].upper() + ' '
print(f'{new_word}')


# printing out the new sentence containing alternate lower and upper case words.
print(f'THe new sentence with alternate lower and upper case characters is:  {new_word}')